server:
  port: 8085



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/babychen?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    tomcat:
      initial-size: 5
      min-idle: 10
      max-active: 20


  redis:
    host: localhost
    port: 6380
    password:
    timeout: 300ms
    database: 0


logging:
  level: debug

